addRegistres = [

{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1915",ordreParCommune:119},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1916",ordreParCommune:120},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1917",ordreParCommune:121},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1918",ordreParCommune:122},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1919",ordreParCommune:123},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1920",ordreParCommune:124},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1921",ordreParCommune:125},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1922",ordreParCommune:126},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1923",ordreParCommune:127},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1924",ordreParCommune:128},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1925",ordreParCommune:129},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1926",ordreParCommune:130},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1927",ordreParCommune:131},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1928",ordreParCommune:132},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1929",ordreParCommune:133},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1930",ordreParCommune:134},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1931",ordreParCommune:135},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1932",ordreParCommune:136},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1933",ordreParCommune:137},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1934",ordreParCommune:138},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1935",ordreParCommune:139},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1936",ordreParCommune:140},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1937",ordreParCommune:141},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1938",ordreParCommune:142},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1939",ordreParCommune:143},
{nbPages:0,type:"Etat civil",commune:"BrQE7YG2Rxi8Dhf4T",contenu:"Mariages",periode:"1940",ordreParCommune:144},

{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1918",ordreParCommune:137},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1919",ordreParCommune:138},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1920",ordreParCommune:139},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1921",ordreParCommune:140},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1922",ordreParCommune:141},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1923",ordreParCommune:142},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1924",ordreParCommune:143},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1925",ordreParCommune:144},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1926",ordreParCommune:145},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1927",ordreParCommune:146},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1928",ordreParCommune:147},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1929",ordreParCommune:148},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1930",ordreParCommune:149},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1931",ordreParCommune:150},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1932",ordreParCommune:151},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1933",ordreParCommune:152},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1934",ordreParCommune:153},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1935",ordreParCommune:154},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1936",ordreParCommune:155},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1937",ordreParCommune:156},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1938",ordreParCommune:157},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1939",ordreParCommune:158},
{nbPages:0,type:"Etat civil",commune:"yRCXwQWkSbpN8qRLW",contenu:"Mariages",periode:"1940",ordreParCommune:159},




]